# The name of the service
service: auction-service

# The Serverless Framework plugins to be used
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

# The AWS provider configuration
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

# declares that we are defining AWS resources
resources:
  Resources: # the actual resources section
    ActionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

# The configuration for the functions
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions
