# The name of the service
service: auction-service

# The Serverless Framework plugins to be used
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

# The AWS provider configuration
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

# declares that we are defining AWS resources
resources: 
  Resources: # the actual resources section
    AuctionsTable: # the name of our DynamoDB table
      Type: AWS::DynamoDB::Table # specifies that we are defining a DynamoDB table
      Properties: # properties for the table
        TableName: AuctionsTable # name of the table
        BillingMode: PAY_PER_REQUEST # sets the billing mode to "pay-per-request", which means we only pay for what we use
        AttributeDefinitions: # defines the attributes for the table
          - AttributeName: id # defines the "id" attribute
            AttributeType: S # specifies that the "id" attribute is a string
        KeySchema: # defines the primary key for the table
          - AttributeName: id # specifies that the "id" attribute is the primary key
            KeyType: HASH # specifies that the "id" attribute is a partition key

# The configuration for the functions
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions
